### ISSUE TITLE
Elgato Marketplace resource downloading

### ISSUE THREAD

**Issue by cgiesche** [ninjadev64/OpenDeck#32]
Hi ninjadev,

this is rather a discussion than an issue:

Elgato seems to have switched to a new plugin store/market:
https://marketplace.elgato.com/stream-deck/plugins

Your (great!) app seems to use the "old" plugin repository that contains more and more outdated plugin versions. Do you think it is possible to migrate/integrate the new store?
It seems to be a bit more "closed" as you have to login to install plugins. It somehow interacts with the original streamdeck application (via custom links) which then downloads and unpacks the plugin.

**Comment by ninjadev64** [comment]
Hey there!

OpenDeck currently uses not the old Elgato App Store, but an archive of it (held at plugins.amankhanna.me) that I had the foresight to make when I saw the direction Elgato was going with their icon packs.

Implementing downloading plugins from the new Marketplace may prove difficult as authentication is required to download resources, especially considering that some resources require payment.

The long-term plan is to populate the catalogue of open-source plugins with more entries, as well as work with plugin developers (like yourself, HA plugin I believe?) to support Linux natively (without Wine).

This has been progressing recently, with the addition of a `manifest.linux.json` file due to Elgato's DistributionTool's complaints about non-standard properties as well as a website for browsing the catalogue (with similar deep-linking plugin install capabilities as the Marketplace).

**Comment by nekename** [comment]
If anyone comes across this, there are now instructions for downloading plugins from the Elgato Marketplace [here](https://github.com/nekename/OpenDeck/wiki/0.-Elgato-Marketplace).
